---
- hosts: target
  vars:
    web_port: 8080
    message: Hello Hana
  
  tasks:
  - yum:
      name: httpd
      state: installed
  - template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
  - service:
      name: httpd
      enabled: true
      #state: restarted
      state: started
  - template:
      src: index.html.j2
      dest: /var/www/html/index.html
  - firewalld:
      port: "{{ web_port }}/tcp"
      immediate: yes
      permanent: yes
      state: enabled