---
# tasks file for web
- yum:
    name: httpd, php
    state: installed
  when:
    - ansible_os_family == "RedHat"
- apt:
    name: apache2, php
    state: present
  when:
    - ansible_os_family == "Debian"
- template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
  - "Restart Web Server"
- service:
    name: httpd
    enabled: true
    state: started
  when:
    - ansible_os_family == "RedHat"
- service:
    name: apache2
    enabled: true
    state: started
  when:
    - ansible_os_family == "Debian"
- template:
    src: "{{ item }}.j2"
    dest: "/var/www/html/{{ item }}"
  loop:
    - "index.html"
    - "index.php"
- firewalld:
    port: "{{ web_port }}/tcp"
    immediate: yes
    permanent: yes
    state: enabled
  when:
    - ansible_os_family == "RedHat"
