---
- hosts: target
  gather_facts: no

  tasks:
  - command: hostname
    register: comm_result
    ignore_errors: true

  - debug:
      msg: "{{ comm_result }}"
  
  - debug:
      msg: "Changed"
    #when: comm_result.changed == true
    when: comm_result is changed

  - debug:
      msg: "Skipped"
    when: comm_result is skipped